FROM bomarconi/pnpm:node-lts-0.4


WORKDIR /srv

COPY . .

RUN pwd
RUN ls
RUN pnpm install
RUN pnpm -F nest-grpc-starter-2 prisma:photo
RUN pnpm -F nest-grpc-starter-2 prisma:schema
RUN pnpm -F nest-grpc-starter-2 build

CMD ["pnpm", "-F", "nest-grpc-starter-2", "start:prod"]